services:
  netalertx:
    container_name: netalertx
    image: "ghcr.io/jokob-sk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./db:/app/db      
      - ./logs:/app/log
      - type: tmpfs
        target: /app/api
    environment:
      - TZ=America/New_York      
      - PORT=20211

    labels:
      - "org.networkingtitan.environment=production"
      - app=monitoring
      - "maintainer=admin@networkingtitan.com"
      - "org.networkingtitan.project=observability"
      - "org.networkingtitan.environment=production"
      - "org.opencontainers.image.description=homelab_scan"


    logging:
      driver: loki
      options:
        loki-url: "https://loki.networkingtitan.com/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"      
