---
- name: Install Linux Packages
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install neofetch, ncdu, btop
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - neofetch
        - ncdu
        - btop
