services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    ports:
      - "8899:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - ./watchtower.env