services:
    uptime-kuma:
        image: 'louislam/uptime-kuma:latest'
        container_name: uptime-kuma
        volumes:
            - './data:/app/data'
        ports:
            - '3009:3001'
        restart: always

        logging:
            driver: syslog
            options:
                syslog-address: "udp://192.168.50.198:1555"
                tag: "uptime-kuma/{{.Name}}/{{.ID}}"
