services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - "3009:3001"
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "https://loki.networkingtitan.com/loki/api/v1/push"
        loki-retries: "2"
        loki-max-backoff: "800ms"
        loki-timeout: "1s"
        mode: "non-blocking"

