services:
    web-check:
        image: lissy93/web-check
        ports:
            - '6000:3000'

        logging:
         driver: loki
         options:
            loki-url: "https://loki.networkingtitan.com/loki/api/v1/push"
            loki-retries: 2
            loki-max-backoff: 800ms
            loki-timeout: 1s
            keep-file: "true"
            mode: "non-blocking"