services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=30d
      - --storage.tsdb.retention.size=2GB
      - --web.enable-lifecycle
    volumes:
      - /home/michael/projects/dockers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /home/michael/projects/dockers/prometheus/data/prometheus:/prometheus

    networks:
      - monitoring
      
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.1
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring  

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    ports:
      - 8089:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped
    networks:
      - monitoring 
      
  snmp_exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp_exporter
    restart: unless-stopped
    ports:
      - 9116:9116
      - 161:161/udp
    volumes:
      - /home/michael/projects/dockers/prometheus/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3006:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=shotokan1   # set your own strong password
    volumes:
      - /home/michael/projects/dockers/prometheus/grafana/data:/var/lib/grafana

    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
