services:
    dozzle:
        image: 'amir20/dozzle:latest'
        ports:
            - '8892:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'

        healthcheck:
          test: ["CMD", "/dozzle", "healthcheck"]
          interval: 3s
          timeout: 30s
          retries: 5
          start_period: 30s    
        
        environment:
            - DOZZLE_REMOTE_AGENT=192.168.2.5:7007,192.168.3.3:7007
            - TZ="America\New_York"