services:
    semaphore:
        ports:
            - 3333:3000
        image: public.ecr.aws/semaphore/pro/server:v2.16.18
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
            SEMAPHORE_EMAIL_ALERT: "True"
            SEMAPHORE_EMAIL_SENDER: "admin@networkingtitan.com"
            SEMAPHORE_EMAIL_HOST: "smtp.zoho.com"
            SEMAPHORE_EMAIL_PORT: "587"
            SEMAPHORE_EMAIL_USERNAME: "admin@networkingtitan.com"
            SEMAPHORE_EMAIL_PASSWORD: ${EMAIL_PASSWORD}
            SEMAPHORE_EMAIL_SECURE: "True"
            SEMAPHORE_EMAIL_TLS: "True"
        volumes:
            - /home/michael/projects/dockers/semaphore_ui/data:/var/lib/semaphore
            - /home/michael/projects/dockers/semaphore_ui/config:/etc/semaphore
            - /home/michael/projects/dockers/semaphore_ui/temp:/tmp/semaphore

        logging:
         driver: loki
         options:
            loki-url: "https://loki.networkingtitan.com/loki/api/v1/push"
            loki-retries: 2
            loki-max-backoff: 800ms
            loki-timeout: 1s
            keep-file: "true"
            mode: "non-blocking"