services:
    freshrss:
        image: freshrss/freshrss
        container_name: freshrss
        env_file:
        - .env
        volumes:
            - '/home/michael/projects/dockers/freshrss/freshrss_extensions:/var/www/FreshRSS/extensions'
            - '/home/michael/projects/dockers/freshrss/freshrss_data:/var/www/FreshRSS/data'
        environment:
            CRON_MIN: "1,31"
            TZ: UTC
        ports:
            - '8080:80'

        logging:
         driver: loki
         options:
            loki-url: "https://loki.networkingtitan.com/loki/api/v1/push"
            loki-retries: 2
            loki-max-backoff: 800ms
            loki-timeout: 1s
            keep-file: "true"
            mode: "non-blocking"    
            