services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      portainer_agent_net:
        ipv4_address: 172.40.0.2

networks:
  portainer_agent_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24
