services:
  netalertx:
    container_name: netalertx
    image: "ghcr.io/jokob-sk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./db:/app/db      
      - ./logs:/app/log
      - type: tmpfs
        target: /app/api
    environment:
      - TZ=America/New_York      
      - PORT=20211

    logging:
       driver: syslog
       options:
          syslog-address: "udp://192.168.50.198:1555"
          tag: "netalertx/{{.Name}}/{{.ID}}"
